language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

sudo: false
dist: trusty

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --dev --no-interaction --prefer-dist

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -v --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
 - if [[ $(phpenv version-name) =~ 7.1 ]] ; then php vendor/bin/coveralls -v; fi
 - if [[ $(phpenv version-name) =~ 7.1 ]] ; then php vendor/bin/test-reporter; fi
